Repository microsoft/BotBuilder-Samples, pull requests merged in 2020-03, with the labels that each got.

#2232 use onEndOfConversation in JS samples
  samples/javascript_nodejs/80.skills-simple-bot-to-bot/echo-skill-bot/bot.js
  samples/javascript_nodejs/80.skills-simple-bot-to-bot/simple-root-bot/rootBot.js
Labels: Skills

#2237 Updated aiohttp samples to use botbuilder-integration-aoihttp
  generators/python/app/templates/core/{{cookiecutter.bot_name}}/requirements.txt
  generators/python/app/templates/echo/{{cookiecutter.bot_name}}/requirements.txt
  generators/python/app/templates/empty/{{cookiecutter.bot_name}}/requirements.txt
  samples/python/02.echo-bot/requirements.txt
  samples/python/03.welcome-user/requirements.txt
  samples/python/05.multi-turn-prompt/requirements.txt
  samples/python/06.using-cards/requirements.txt
  samples/python/07.using-adaptive-cards/requirements.txt
  samples/python/08.suggested-actions/requirements.txt
  samples/python/11.qnamaker/requirements.txt
  samples/python/13.core-bot/requirements.txt
  samples/python/14.nlp-with-dispatch/requirements.txt
  samples/python/15.handling-attachments/requirements.txt
  samples/python/16.proactive-messages/requirements.txt
  samples/python/17.multilingual-bot/requirements.txt
  samples/python/18.bot-authentication/requirements.txt
  samples/python/19.custom-dialogs/requirements.txt
  samples/python/21.corebot-app-insights/requirements.txt
  samples/python/23.facebook-events/requirements.txt
  samples/python/24.bot-authentication-msgraph/requirements.txt
  samples/python/42.scaleout/requirements.txt
  samples/python/43.complex-dialog/requirements.txt
  samples/python/44.prompt-for-user-input/requirements.txt
  samples/python/45.state-management/requirements.txt
  samples/python/46.teams-auth/requirements.txt
  samples/python/47.inspection/requirements.txt
  samples/python/50.teams-messaging-extension-search/requirements.txt
  samples/python/51.teams-messaging-extensions-action/requirements.txt
  samples/python/52.teams-messaging-extensions-search-auth-config/requirements.txt
  samples/python/53.teams-messaging-extensions-action-preview/requirements.txt
  samples/python/54.teams-task-module/requirements.txt
  samples/python/55.teams-link-unfurling/requirements.txt
  samples/python/56.teams-file-upload/requirements.txt
  samples/python/57.teams-conversation-bot/requirements.txt
  samples/python/58.teams-start-thread-in-channel/requirements.txt
  samples/python/80.skills-simple-bot-to-bot/echo-skill-bot/requirements.txt
  samples/python/80.skills-simple-bot-to-bot/simple-root-bot/requirements.txt
Labels: R8

#2199 [Do not merge] Adaptive Expressions R8 doc updates
  experimental/common-expression-language/README.md
Labels: R8 Post Release

#2178 Python slack adapter sample
  samples/python/60.slack-adapter/README.md
  samples/python/60.slack-adapter/app.py
  samples/python/60.slack-adapter/bots/__init__.py
  samples/python/60.slack-adapter/bots/echo_bot.py
  samples/python/60.slack-adapter/config.py
  samples/python/60.slack-adapter/deploymentTemplates/template-with-new-rg.json
  samples/python/60.slack-adapter/deploymentTemplates/template-with-preexisting-rg.json
  samples/python/60.slack-adapter/requirements.txt
  samples/python/60.slack-adapter/resources/InteractiveMessage.json
Labels: R8

#2256 Python: using botbuilder-integration-aiohttp in 60.slack-adapter
  samples/python/60.slack-adapter/requirements.txt
Labels: R8
