Repository microsoft/BotBuilder-Samples, pull requests merged in 2020-01, with the labels that each got.

#1861 [botkit] Add Facebook Adapter Bot sample
  samples/csharp_dotnetcore/61.facebook-adapter/Adapters/BotFrameworkAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/61.facebook-adapter/Adapters/FacebookAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/61.facebook-adapter/Bots/EchoBot.cs
  samples/csharp_dotnetcore/61.facebook-adapter/Controllers/BotController.cs
  samples/csharp_dotnetcore/61.facebook-adapter/Controllers/FacebookController.cs
  samples/csharp_dotnetcore/61.facebook-adapter/DeploymentTemplates/template-with-new-rg.json
  samples/csharp_dotnetcore/61.facebook-adapter/DeploymentTemplates/template-with-preexisting-rg.json
  samples/csharp_dotnetcore/61.facebook-adapter/FacebookAdapterBot.csproj
  samples/csharp_dotnetcore/61.facebook-adapter/Program.cs
  samples/csharp_dotnetcore/61.facebook-adapter/Properties/launchSettings.json
  samples/csharp_dotnetcore/61.facebook-adapter/README.md
  samples/csharp_dotnetcore/61.facebook-adapter/Resources/ButtonTemplatePayload.json
  samples/csharp_dotnetcore/61.facebook-adapter/Resources/GenericTemplatePayload.json
  samples/csharp_dotnetcore/61.facebook-adapter/Resources/MediaTemplatePayload.json
  samples/csharp_dotnetcore/61.facebook-adapter/Startup.cs
  samples/csharp_dotnetcore/61.facebook-adapter/appsettings.Development.json
  samples/csharp_dotnetcore/61.facebook-adapter/appsettings.json
  samples/csharp_dotnetcore/61.facebook-adapter/wwwroot/default.htm
  samples/csharp_dotnetcore/csharp_dotnetcore.sln
Labels: R8

#1850 [botkit] Add twilio Echo bot sample
  samples/csharp_dotnetcore/63.twilio-adapter/Adapters/BotFrameworkAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/63.twilio-adapter/Adapters/TwilioAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/63.twilio-adapter/Bots/EchoBot.cs
  samples/csharp_dotnetcore/63.twilio-adapter/Controllers/BotController.cs
  samples/csharp_dotnetcore/63.twilio-adapter/Controllers/TwilioController.cs
  samples/csharp_dotnetcore/63.twilio-adapter/DeploymentTemplates/template-with-new-rg.json
  samples/csharp_dotnetcore/63.twilio-adapter/DeploymentTemplates/template-with-preexisting-rg.json
  samples/csharp_dotnetcore/63.twilio-adapter/Program.cs
  samples/csharp_dotnetcore/63.twilio-adapter/Properties/launchSettings.json
  samples/csharp_dotnetcore/63.twilio-adapter/README.md
  samples/csharp_dotnetcore/63.twilio-adapter/Startup.cs
  samples/csharp_dotnetcore/63.twilio-adapter/TwilioAdapterBot.csproj
  samples/csharp_dotnetcore/63.twilio-adapter/appsettings.Development.json
  samples/csharp_dotnetcore/63.twilio-adapter/appsettings.json
  samples/csharp_dotnetcore/63.twilio-adapter/wwwroot/default.htm
  samples/csharp_dotnetcore/csharp_dotnetcore.sln
Labels: R8

#1858 [botkit] Add Slack Adapter Bot sample
  samples/csharp_dotnetcore/60.slack-adapter/Adapters/BotFrameworkAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/60.slack-adapter/Adapters/SlackAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/60.slack-adapter/Bots/EchoBot.cs
  samples/csharp_dotnetcore/60.slack-adapter/Controllers/BotController.cs
  samples/csharp_dotnetcore/60.slack-adapter/Controllers/SlackController.cs
  samples/csharp_dotnetcore/60.slack-adapter/DeploymentTemplates/template-with-new-rg.json
  samples/csharp_dotnetcore/60.slack-adapter/DeploymentTemplates/template-with-preexisting-rg.json
  samples/csharp_dotnetcore/60.slack-adapter/Program.cs
  samples/csharp_dotnetcore/60.slack-adapter/Properties/launchSettings.json
  samples/csharp_dotnetcore/60.slack-adapter/README.md
  samples/csharp_dotnetcore/60.slack-adapter/Resources/InteractiveMessage.json
  samples/csharp_dotnetcore/60.slack-adapter/SlackAdapterBot.csproj
  samples/csharp_dotnetcore/60.slack-adapter/Startup.cs
  samples/csharp_dotnetcore/60.slack-adapter/appsettings.Development.json
  samples/csharp_dotnetcore/60.slack-adapter/appsettings.json
  samples/csharp_dotnetcore/60.slack-adapter/wwwroot/default.htm
  samples/csharp_dotnetcore/csharp_dotnetcore.sln
Labels: R8

#1857 [botkit] Add Webex Adapter Bot sample
  samples/csharp_dotnetcore/62.webex-adapter/Adapters/BotFrameworkAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/62.webex-adapter/Adapters/WebexAdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/62.webex-adapter/Bots/EchoBot.cs
  samples/csharp_dotnetcore/62.webex-adapter/Controllers/BotController.cs
  samples/csharp_dotnetcore/62.webex-adapter/Controllers/WebexController.cs
  samples/csharp_dotnetcore/62.webex-adapter/DeploymentTemplates/template-with-new-rg.json
  samples/csharp_dotnetcore/62.webex-adapter/DeploymentTemplates/template-with-preexisting-rg.json
  samples/csharp_dotnetcore/62.webex-adapter/Program.cs
  samples/csharp_dotnetcore/62.webex-adapter/Properties/launchSettings.json
  samples/csharp_dotnetcore/62.webex-adapter/README.md
  samples/csharp_dotnetcore/62.webex-adapter/Resources/adaptive_card.json
  samples/csharp_dotnetcore/62.webex-adapter/Startup.cs
  samples/csharp_dotnetcore/62.webex-adapter/WebexAdapterBot.csproj
  samples/csharp_dotnetcore/62.webex-adapter/WebexAdapterBot.sln
  samples/csharp_dotnetcore/62.webex-adapter/appsettings.Development.json
  samples/csharp_dotnetcore/62.webex-adapter/appsettings.json
  samples/csharp_dotnetcore/62.webex-adapter/wwwroot/default.htm
  samples/csharp_dotnetcore/csharp_dotnetcore.sln
Labels: R8

#2113 Add quickstart and pointer to generation to adaptive dialog documentation.
  experimental/adaptive-dialog/README.md
  experimental/adaptive-dialog/docs/generating-dialogs.md
Labels: adaptive

#2144 [Teams] Adding sample to show how to start new thread
  samples/python/58.teams-start-thread-in-channel/README.md
  samples/python/58.teams-start-thread-in-channel/app.py
  samples/python/58.teams-start-thread-in-channel/bots/__init__.py
  samples/python/58.teams-start-thread-in-channel/bots/teams_start_thread_in_channel.py
  samples/python/58.teams-start-thread-in-channel/config.py
  samples/python/58.teams-start-thread-in-channel/deploymentTemplates/template-with-new-rg.json
  samples/python/58.teams-start-thread-in-channel/deploymentTemplates/template-with-preexisting-rg.json
  samples/python/58.teams-start-thread-in-channel/requirements.txt
  samples/python/58.teams-start-thread-in-channel/teams_app_manifest/icon-color.png
  samples/python/58.teams-start-thread-in-channel/teams_app_manifest/icon-outline.png
  samples/python/58.teams-start-thread-in-channel/teams_app_manifest/manifest.json
Labels: R8, teams

#2145 [Teams] Adding sample to creating new thread in Team (C#)
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/AdapterWithErrorHandler.cs
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/Bots/TeamsStartNewThreadInTeam.cs
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/Controllers/BotController.cs
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/DeploymentTemplates/new-rg-parameters.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/DeploymentTemplates/preexisting-rg-parameters.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/DeploymentTemplates/template-with-new-rg.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/DeploymentTemplates/template-with-preexisting-rg.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/Program.cs
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/Properties/launchSettings.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/README.md
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/Startup.cs
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/TeamsAppManifest/icon-color.png
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/TeamsAppManifest/icon-outline.png
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/TeamsAppManifest/manifest.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/TeamsStartNewThreadInTeam.csproj
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/TeamsStartNewThreadInTeam.sln
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/appsettings.json
  samples/csharp_dotnetcore/58.teams-start-new-thread-in-channel/wwwroot/default.html
  samples/csharp_dotnetcore/csharp_dotnetcore.sln
Labels: R8, teams
